name: EGG CI
on:
  workflow_call:
    inputs:
      working-directory:
        description: Working directory to use
        type: string
        default: ./
defaults:
  run:
    working-directory: ${{ github.event.inputs.working-directory }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        run: make build
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        run: test -z $(gofmt -l .)
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Lint
        run: go vet ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build, format, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Test
        run: make test
